"""add_vendor_quotes_and_cargo_requests

Revision ID: 337ad255a2ab
Revises: 6b1cf7a1a16a
Create Date: 2026-09-23 16:20:06.679197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '337ad255a2ab'
down_revision: Union[str, Sequence[str], None] = '6b1cf7a1a16a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendor_quotes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('quote_request_label', sa.String(), nullable=True),
    sa.Column('broker_name', sa.String(), nullable=False),
    sa.Column('vessel_type', sa.String(), nullable=False),
    sa.Column('quoted_rate_usd_per_mt', sa.Float(), nullable=False),
    sa.Column('delivery_days', sa.Integer(), nullable=False),
    sa.Column('valid_until', sa.Date(), nullable=False),
    sa.Column('is_sample_data', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendor_quotes_id'), 'vendor_quotes', ['id'], unique=False)
    op.create_table('cargo_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=True),
    sa.Column('cargo_type_id', sa.Integer(), nullable=True),
    sa.Column('quantity_mt', sa.Float(), nullable=False),
    sa.Column('destination_port_id', sa.Integer(), nullable=True),
    sa.Column('requested_by', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('merged_into_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cargo_type_id'], ['reference_cargo_types.id'], ),
    sa.ForeignKeyConstraint(['destination_port_id'], ['reference_ports.id'], ),
    sa.ForeignKeyConstraint(['merged_into_id'], ['cargo_requests.id'], ),
    sa.ForeignKeyConstraint(['plant_id'], ['reference_plants.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cargo_requests_id'), 'cargo_requests', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cargo_requests_id'), table_name='cargo_requests')
    op.drop_table('cargo_requests')
    op.drop_index(op.f('ix_vendor_quotes_id'), table_name='vendor_quotes')
    op.drop_table('vendor_quotes')
    # ### end Alembic commands ###
