"""create_initial_tables

Revision ID: 6b1cf7a1a16a
Revises: 
Create Date: 2026-09-23 16:17:37.999513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b1cf7a1a16a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disruption_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keyword_matched', sa.String(), nullable=True),
    sa.Column('headline_text', sa.Text(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('matched_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disruption_alerts_id'), 'disruption_alerts', ['id'], unique=False)
    op.create_table('reference_cargo_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cargo_name', sa.String(), nullable=False),
    sa.Column('density_mt_per_cbm', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cargo_name')
    )
    op.create_index(op.f('ix_reference_cargo_types_id'), 'reference_cargo_types', ['id'], unique=False)
    op.create_table('reference_plants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plant_name', sa.String(), nullable=False),
    sa.Column('location_city', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plant_name')
    )
    op.create_index(op.f('ix_reference_plants_id'), 'reference_plants', ['id'], unique=False)
    op.create_table('reference_ports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('port_name', sa.String(), nullable=False),
    sa.Column('locode', sa.String(), nullable=True),
    sa.Column('max_loa_m', sa.Float(), nullable=False),
    sa.Column('max_beam_m', sa.Float(), nullable=False),
    sa.Column('max_draft_m', sa.Float(), nullable=False),
    sa.Column('max_dwt_mt', sa.Integer(), nullable=False),
    sa.Column('has_lightering', sa.Boolean(), nullable=True),
    sa.Column('lightering_note', sa.Text(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('port_name')
    )
    op.create_index(op.f('ix_reference_ports_id'), 'reference_ports', ['id'], unique=False)
    op.create_table('reference_vessel_classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_name', sa.String(), nullable=False),
    sa.Column('dwt_min', sa.Integer(), nullable=False),
    sa.Column('dwt_max', sa.Integer(), nullable=False),
    sa.Column('typical_draft_m', sa.Float(), nullable=False),
    sa.Column('typical_loa_m', sa.Float(), nullable=False),
    sa.Column('typical_beam_m', sa.Float(), nullable=False),
    sa.Column('avg_speed_knots', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('class_name')
    )
    op.create_index(op.f('ix_reference_vessel_classes_id'), 'reference_vessel_classes', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('origin_country', sa.String(), nullable=False),
    sa.Column('origin_port', sa.String(), nullable=False),
    sa.Column('destination_port', sa.String(), nullable=False),
    sa.Column('commodity', sa.String(), nullable=False),
    sa.Column('parcel_tonnage', sa.Float(), nullable=False),
    sa.Column('recommended_vessel', sa.String(), nullable=False),
    sa.Column('predicted_rate_pmt', sa.Float(), nullable=False),
    sa.Column('benchmark_spot_pmt', sa.Float(), nullable=False),
    sa.Column('estimated_savings_usd', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analyses_id'), 'analyses', ['id'], unique=False)
    op.create_index(op.f('ix_analyses_user_id'), 'analyses', ['user_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('affected_record_id', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('logged_at', sa.DateTime(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_table('context_objects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('route_distance_nm', sa.Float(), nullable=True),
    sa.Column('inferred_vessel_class', sa.String(), nullable=True),
    sa.Column('origin_lat', sa.Float(), nullable=True),
    sa.Column('origin_lon', sa.Float(), nullable=True),
    sa.Column('destination_lat', sa.Float(), nullable=True),
    sa.Column('destination_lon', sa.Float(), nullable=True),
    sa.Column('context_resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('analysis_id')
    )
    op.create_index(op.f('ix_context_objects_id'), 'context_objects', ['id'], unique=False)
    op.create_table('decision_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=True),
    sa.Column('chosen_vessel_class', sa.String(), nullable=True),
    sa.Column('chosen_port_id', sa.Integer(), nullable=True),
    sa.Column('chosen_day_rate', sa.Float(), nullable=True),
    sa.Column('was_override', sa.Boolean(), nullable=True),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.Column('decided_by', sa.Integer(), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('analysis_id')
    )
    op.create_index(op.f('ix_decision_records_id'), 'decision_records', ['id'], unique=False)
    op.create_table('enrichment_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=True),
    sa.Column('data_key', sa.String(), nullable=False),
    sa.Column('data_value', sa.Text(), nullable=False),
    sa.Column('data_classification', sa.String(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.Column('is_stale', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enrichment_cache_data_key'), 'enrichment_cache', ['data_key'], unique=False)
    op.create_index(op.f('ix_enrichment_cache_id'), 'enrichment_cache', ['id'], unique=False)
    op.create_table('feasibility_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=True),
    sa.Column('vessel_class', sa.String(), nullable=False),
    sa.Column('port_id', sa.Integer(), nullable=True),
    sa.Column('port_name', sa.String(), nullable=True),
    sa.Column('draft_pass', sa.Boolean(), nullable=True),
    sa.Column('loa_pass', sa.Boolean(), nullable=True),
    sa.Column('beam_pass', sa.Boolean(), nullable=True),
    sa.Column('dwt_pass', sa.Boolean(), nullable=True),
    sa.Column('overall_feasible', sa.Boolean(), nullable=True),
    sa.Column('requires_lightering', sa.Boolean(), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feasibility_results_id'), 'feasibility_results', ['id'], unique=False)
    op.create_table('forecast_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=True),
    sa.Column('p10_usd_per_mt', sa.Float(), nullable=True),
    sa.Column('p50_usd_per_mt', sa.Float(), nullable=True),
    sa.Column('p90_usd_per_mt', sa.Float(), nullable=True),
    sa.Column('arima_baseline_usd_per_mt', sa.Float(), nullable=True),
    sa.Column('confidence_label', sa.String(), nullable=True),
    sa.Column('model_used', sa.String(), nullable=True),
    sa.Column('forecast_generated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('analysis_id')
    )
    op.create_index(op.f('ix_forecast_results_id'), 'forecast_results', ['id'], unique=False)
    op.create_table('landed_costs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=True),
    sa.Column('freight_rate_usd_per_mt', sa.Float(), nullable=False),
    sa.Column('baf_surcharge_usd_per_mt', sa.Float(), nullable=True),
    sa.Column('usd_inr_rate', sa.Float(), nullable=True),
    sa.Column('total_usd_per_mt', sa.Float(), nullable=False),
    sa.Column('total_inr_per_mt', sa.Float(), nullable=False),
    sa.Column('total_inr', sa.Float(), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('analysis_id')
    )
    op.create_index(op.f('ix_landed_costs_id'), 'landed_costs', ['id'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('vessel_class', sa.String(), nullable=False),
    sa.Column('port_id', sa.Integer(), nullable=True),
    sa.Column('port_name', sa.String(), nullable=True),
    sa.Column('cost_score', sa.Float(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('coverage_fit_score', sa.Float(), nullable=True),
    sa.Column('total_score', sa.Float(), nullable=True),
    sa.Column('cost_score_breakdown', sa.Text(), nullable=True),
    sa.Column('is_emergency_mode', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_id'), 'recommendations', ['id'], unique=False)
    op.create_table('risk_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=True),
    sa.Column('risk_category', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('signal_description', sa.Text(), nullable=True),
    sa.Column('data_source', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_results_id'), 'risk_results', ['id'], unique=False)
    op.create_table('stockout_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=True),
    sa.Column('days_to_stockout', sa.Float(), nullable=True),
    sa.Column('days_to_best_window', sa.Float(), nullable=True),
    sa.Column('is_at_risk', sa.Boolean(), nullable=True),
    sa.Column('alert_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stockout_alerts_id'), 'stockout_alerts', ['id'], unique=False)
    op.create_table('regret_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('decision_record_id', sa.Integer(), nullable=True),
    sa.Column('regret_pct', sa.Float(), nullable=True),
    sa.Column('chosen_day_rate', sa.Float(), nullable=True),
    sa.Column('best_rate_in_window', sa.Float(), nullable=True),
    sa.Column('window_start', sa.Date(), nullable=True),
    sa.Column('window_end', sa.Date(), nullable=True),
    sa.Column('computed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['decision_record_id'], ['decision_records.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('decision_record_id')
    )
    op.create_index(op.f('ix_regret_scores_id'), 'regret_scores', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_regret_scores_id'), table_name='regret_scores')
    op.drop_table('regret_scores')
    op.drop_index(op.f('ix_stockout_alerts_id'), table_name='stockout_alerts')
    op.drop_table('stockout_alerts')
    op.drop_index(op.f('ix_risk_results_id'), table_name='risk_results')
    op.drop_table('risk_results')
    op.drop_index(op.f('ix_recommendations_id'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_landed_costs_id'), table_name='landed_costs')
    op.drop_table('landed_costs')
    op.drop_index(op.f('ix_forecast_results_id'), table_name='forecast_results')
    op.drop_table('forecast_results')
    op.drop_index(op.f('ix_feasibility_results_id'), table_name='feasibility_results')
    op.drop_table('feasibility_results')
    op.drop_index(op.f('ix_enrichment_cache_id'), table_name='enrichment_cache')
    op.drop_index(op.f('ix_enrichment_cache_data_key'), table_name='enrichment_cache')
    op.drop_table('enrichment_cache')
    op.drop_index(op.f('ix_decision_records_id'), table_name='decision_records')
    op.drop_table('decision_records')
    op.drop_index(op.f('ix_context_objects_id'), table_name='context_objects')
    op.drop_table('context_objects')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_analyses_user_id'), table_name='analyses')
    op.drop_index(op.f('ix_analyses_id'), table_name='analyses')
    op.drop_table('analyses')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_reference_vessel_classes_id'), table_name='reference_vessel_classes')
    op.drop_table('reference_vessel_classes')
    op.drop_index(op.f('ix_reference_ports_id'), table_name='reference_ports')
    op.drop_table('reference_ports')
    op.drop_index(op.f('ix_reference_plants_id'), table_name='reference_plants')
    op.drop_table('reference_plants')
    op.drop_index(op.f('ix_reference_cargo_types_id'), table_name='reference_cargo_types')
    op.drop_table('reference_cargo_types')
    op.drop_index(op.f('ix_disruption_alerts_id'), table_name='disruption_alerts')
    op.drop_table('disruption_alerts')
    # ### end Alembic commands ###
